Attribute VB_Name = "Mod_Polylines"
Sub polylines(ssetPolylines)
    
    For Each entObj In ssetPolylines
    
    Dim retCoord As Variant
        retCoord = entObj.Coordinates
        For Each coordinate In retCoord
            counter = counter + 1
        Next
        
        ReDim points(0 To counter - 1) As Double
        ReDim coordinate_array(counter)
        i = 0
        For Each coordinate In retCoord
            points(i) = coordinate
        i = i + 1
        Next
        
        For i = 0 To counter - 1 Step 2
            Ax0 = points(i)
            Ay0 = points(i + 1)
            Ax = 0: Ay = 0
            If index = "Similarity" Then
                points(i) = xEstimation(1) + xEstimation(2) * Ax0 + xEstimation(3) * Ay0
                points(i + 1) = xEstimation(4) + xEstimation(2) * Ay0 - xEstimation(3) * Ax0
            Else
                For j = 1 To met
                    Ax = xEstimation(j) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
                    Ay = xEstimation(j + met) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
                    AxFinal = AxFinal + Ax
                    AyFinal = AyFinal + Ay
                Next j
                points(i) = AxFinal
                points(i + 1) = AyFinal
                AxFinal = 0: AyFinal = 0
            End If
        Next i

        Call chAddLayer
        
        ' Create a lightweight Polyline object in model space
        Dim LWentObj As AcadLWPolyline
        Set LWentObj = ThisDrawing.ModelSpace.AddLightWeightPolyline(points)
        ZoomAll
        counter = 0
    Next
  
End Sub
