Attribute VB_Name = "Mod_Block"
Dim blockRefObj As AcadBlockReference
Dim mtextString As String
Dim insertionPoint(0 To 2) As Double

Sub block(ssetBlock)
    
    For Each entObj In ssetBlock
        
        ' Return the current value of the insertion point
        Dim currInsertionPoint As Variant
        currInsertionPoint = entObj.insertionPoint
        
        Ax0 = currInsertionPoint(0)
        Ay0 = currInsertionPoint(1)
        Ax = 0: Ay = 0
        If index = "Similarity" Then
            currInsertionPoint(0) = xEstimation(1) + xEstimation(2) * Ax0 + xEstimation(3) * Ay0
            currInsertionPoint(1) = xEstimation(4) + xEstimation(2) * Ay0 - xEstimation(3) * Ax0
        Else
            For j = 1 To met
            Ax = xEstimation(j) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
            Ay = xEstimation(j + met) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
            AxFinal = AxFinal + Ax
            AyFinal = AyFinal + Ay
            Next j
            currInsertionPoint(0) = AxFinal
            currInsertionPoint(1) = AyFinal
            AxFinal = 0: AyFinal = 0
        End If

        ' Define the text object
        onoma = entObj.Name
        insertionPoint(0) = currInsertionPoint(0): insertionPoint(1) = currInsertionPoint(1): insertionPoint(2) = 0
    
        Call chAddLayer
        
        ' Create the text object in model space
        Set blockRefObj = ThisDrawing.ModelSpace.InsertBlock(insertionPoint, onoma, 1, 1, 1, 1, 0)

        ZoomAll
    Next

End Sub


