Attribute VB_Name = "Mod_Lines"
Sub CLines(ssetLines)
    Dim PtA As Variant, PtB As Variant
    Dim Ax0 As Double, Ay0 As Double
    Dim Bx0 As Double, By0 As Double
    Dim AxFinal, AyFinal, Bx_tel, By_tel As Variant
    Dim Ax, Ay, bxtel, bytel As Variant
   
    ReDim AX(1 To grammes): ReDim AY(1 To grammes): ReDim BX(1 To grammes): ReDim BY(1 To grammes)

    i = 0
    For Each entObj In ssetLines
        ' Find the start and endpoints for the line
        PtA = entObj.startPoint
        PtB = entObj.endPoint
        
        Ax0 = PtA(0): Ay0 = PtA(1): Bx0 = PtB(0): By0 = PtB(1)
        Ax = 0: Ay = 0
        
        If index = "Similarity" Then
            AX(i + 1) = xEstimation(1) + xEstimation(2) * Ax0 + xEstimation(3) * Ay0
            AY(i + 1) = xEstimation(4) + xEstimation(2) * Ay0 - xEstimation(3) * Ax0
            BX(i + 1) = xEstimation(1) + xEstimation(2) * Bx0 + xEstimation(3) * By0
            BY(i + 1) = xEstimation(4) + xEstimation(2) * By0 - xEstimation(3) * Bx0
        Else
            For j = 1 To met
                Ax = xEstimation(j) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
                Ay = xEstimation(j + met) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
                bxtel = xEstimation(j) * Bx0 ^ kr(j) * By0 ^ lr(j)
                bytel = xEstimation(j + met) * Bx0 ^ kr(j) * By0 ^ lr(j)
                AxFinal = AxFinal + Ax
                AyFinal = AyFinal + Ay
                Bx_tel = Bx_tel + bxtel
                By_tel = By_tel + bytel
            Next j
            AX(i + 1) = AxFinal: AY(i + 1) = AyFinal: BX(i + 1) = Bx_tel: BY(i + 1) = By_tel
            AxFinal = 0: AyFinal = 0: Bx_tel = 0: By_tel = 0
        End If
            i = i + 1
    Next

    Call chAddLayer

    Dim lineObj As AcadLine
    For i = 1 To grammes
        Dim startPoint(0 To 2) As Double
        Dim endPoint(0 To 2) As Double
        startPoint(0) = AX(i): startPoint(1) = AY(i): startPoint(2) = 0
        endPoint(0) = BX(i): endPoint(1) = BY(i): endPoint(2) = 0

        ' Create the line in model space
        Set lineObj = ThisDrawing.ModelSpace.AddLine(startPoint, endPoint)
    
        ZoomAll
    
        startPoint(1) = 0: startPoint(2) = 0: endPoint(1) = 0: endPoint(2) = 0
    Next i
   
End Sub
