Attribute VB_Name = "Mod_MText"
Dim mtextObj As AcadText
Dim mtextString As String
Dim insertionPoint(0 To 2) As Double
Dim height As Double
Sub mtext(ssetMText)

    For Each entObj In ssetMText
    
        ' Return the current value of the insertion point
        Dim currInsertionPoint As Variant
        currInsertionPoint = entObj.insertionPoint
        'MsgBox "The insertion point of the text is " & currInsertionPoint(0) & ", " & currInsertionPoint(1) & ", " & currInsertionPoint(2), vbInformation, "InsertionPoint Example"
        
        Ax0 = currInsertionPoint(0)
        Ay0 = currInsertionPoint(1)
        Ax = 0: Ay = 0
        If index = "Smilarity" Then
            currInsertionPoint(0) = xEstimation(1) + xEstimation(2) * Ax0 + xEstimation(3) * Ay0
            currInsertionPoint(1) = xEstimation(4) + xEstimation(2) * Ay0 - xEstimation(3) * Ax0
        Else
            For j = 1 To met
                Ax = xEstimation(j) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
                Ay = xEstimation(j + met) * Ax0 ^ kr(j) * Ay0 ^ lr(j)
                AxFinal = AxFinal + Ax
                AyFinal = AyFinal + Ay
            Next j
            currInsertionPoint(0) = AxFinal
            currInsertionPoint(1) = AyFinal
            AxFinal = 0: AyFinal = 0
        End If
            ' Define the text object
            TextString = entObj.TextString
            insertionPoint(0) = currInsertionPoint(0): insertionPoint(1) = currInsertionPoint(1): insertionPoint(2) = 0
            height = entObj.height
            
            Call chAddLayer
            
            ' Create the text object in model space
            Set textObj = ThisDrawing.ModelSpace.AddText(TextString, insertionPoint, height)
            ZoomAll
        Next
  
End Sub

