Attribute VB_Name = "Mod_ssets"
Public ssetObj As AcadSelectionSet
Public ssetLines As AcadSelectionSet
Public ssetPolylines As AcadSelectionSet
Public ssetMText As AcadSelectionSet
Public ssetBlock As AcadSelectionSet
Public numberOfLines, numberOfPolyLines, numberOfTexts, numberOfBlocks As Integer
Public entObj As AcadEntity

Sub ssets()
    ' Create the selection set
    Set ssetObj = ThisDrawing.SelectionSets.Add("TEST_SSET")
    
    ' Add objects to a selection set by prompting user to select on the screen
    ssetObj.SelectOnScreen
    
    For Each entObj In ssetObj
        If entObj.EntityName = "AcDbLine" Then
            numberOfLines = numberOfLines + 1
        ElseIf entObj.EntityName = "AcDbPolyline" Then
            numberOfPolyLines = numberOfPolyLines + 1
        ElseIf entObj.EntityName = "AcDbMText" Then
            numberOfTexts = numberOfTexts + 1
        ElseIf entObj.EntityName = "AcDbBlockReference" Then
            numberOfBlocks = numberOfBlocks + 1
        Else
        End If
    Next
    
    On Error Resume Next
    ReDim LineObjs(0 To numberOfLines - 1) As AcadLine
    On Error Resume Next
    ReDim PolylineObjs(0 To numberOfPolyLines - 1) As AcadLWPolyline
    On Error Resume Next
    ReDim MTextObjs(0 To numberOfTexts - 1) As AcadMText
    On Error Resume Next
    ReDim BlockObjs(0 To numberOfBlocks - 1) As AcadBlockReference
    
    ' Create a new selection set
    Set ssetLines = ThisDrawing.SelectionSets.Add("LinesSelectionSet")
    Set ssetPolylines = ThisDrawing.SelectionSets.Add("PLinesSelectionSet")
    Set ssetMText = ThisDrawing.SelectionSets.Add("TextsSelectionSet")
    Set ssetBlock = ThisDrawing.SelectionSets.Add("BlocksSelectionSet")
    
    ssetLines.AddItems LineObjs
    ssetPolylines.AddItems PolylineObjs
    ssetMText.AddItems MTextObjs: ssetBlock.AddItems BlockObjs
    & ", text = " & ssetMText.Count & ", block = " & ssetBlock.Count
    
    ThisDrawing.SelectionSets.Item("TEST_SSET").Delete
End Sub
