Dim numberOfPoints As Single
Dim keywordList As String
Dim returnPnt As Variant
Dim returnPnt2 As Variant

' add point command button
Private Sub addPointButton_Click()
    numberOfPoints = numberOfPoints + 1
    ListBox1.AddItem (numberOfPoints & ") " & TextBox1.Text)
    ListBox2.AddItem (numberOfPoints & ") " & TextBox2.Text)
End Sub

Function removePointFromListBox(listBox As ListBox)
    Dim numberOfPoints As Integer
    numberOfPoints = listBox.ListCount

    'Ensure ListBox contains list items
    Dim selectedIndex As Integer
    selectedIndex = listBox.ListIndex
    If (numberOfPoints >= 1) Then
        'If no selection, choose the last list item.
        If (selectedIndex = -1) Then
            selectedIndex = numberOfPoints - 1
        End If
        basePointsListBox.RemoveItem (selectedIndex)
    End If
End Function


' remove point command button
Private Sub removePointButton_Click()
    removePointFromListBox(basePointsListBox)
    removePointFromListBox(referencePointsListBox)
End Sub

' OK command button
Private Sub okButton_Click() 'KOYMPI "OK"
    degree = degreeTextBox.Text
    parameters = degree + 1
    
    MsgBox parameters
    
    Dim numberOfPoints As Integer
    numberOfPoints = basePointsListBox.ListCount

    Call transformation(parameters, degree, numberOfPoints, ListBox1, ListBox2)
End Sub

' Cancel command button
Private Sub CancelButton_Click()
    Unload Me
End Sub

' 
Private Sub CommandButton6_Click()
On Error Resume Next
Frame2.Enabled = True
Frame3.Enabled = True
Frame4.Enabled = True
ListBox1.Enabled = True
ListBox2.Enabled = True
UserForm3.hide
Dim returnPnt As Variant
Dim returnPnt2 As Variant
numberOfPoints = 0

   Dim Msg, Style, Title, Help, Ctxt, Response, MyString
Msg = "Choose couple of points."    ' Define message.
Style = vbYesNo    ' Define buttons.
Title = " "    ' Define title.
Help = "DEMO.HLP"    ' Define Help file.
Ctxt = 1000    ' Define topic
        ' context.
        ' Display message.
Response = MsgBox(Msg, Style, Title, Help, Ctxt)
Do While Response = vbYes  ' User chose Yes.
    MyString = "Yes"    ' Perform some action.
numberOfPoints = numberOfPoints + 1
       
returnPnt = ThisDrawing.Utility.GetPoint(, "Input point")
    If Err Then
         If StrComp(Err.Description, "User input is a keyword", 1) = 0 Then
         ' One of the keywords was entered
             Dim inputString As String
             Err.Clear
             inputString = ThisDrawing.Utility.GetInput
             MsgBox "You entered the keyword: " & inputString
         Else
             MsgBox "Error selecting the point: " & Err.Description
             Err.Clear
         End If
    
    End If
ThisDrawing.ModelSpace.AddPoint returnPnt
ThisDrawing.ModelSpace.AddText Str(numberOfPoints), returnPnt, 1
ListBox1.AddItem (numberOfPoints & ")" & Str(returnPnt(0)) & "," & Str(returnPnt(1)))

returnPnt = ThisDrawing.Utility.GetPoint(, "Input corresponding point")
ThisDrawing.ModelSpace.AddPoint returnPnt
ThisDrawing.ModelSpace.AddText Str(numberOfPoints), returnPnt, 1
    If Err Then
         If StrComp(Err.Description, "User input is a keyword", 1) = 0 Then
         ' One of the keywords was entered
             Err.Clear
             inputString = ThisDrawing.Utility.GetInput
             MsgBox "You entered the keyword: " & inputString
         Else
             MsgBox "Error selecting the point: " & Err.Description
             Err.Clear
         End If
    
    End If
ListBox2.AddItem (numberOfPoints & ")" & Str(returnPnt(0)) & "," & Str(returnPnt(1)))
Response = MsgBox(Msg, Style, Title, Help, Ctxt)
If Response = vbNo Then
 GoTo 10
End If
Loop ' User chose No.

10:   UserForm3.Show
End Sub

' Polynomial degree textBoox
Private Sub degreeTextBox_Change() 'degree polywnymoy
    degree = degreeTextBox.Text
    metr = 0
    parameters = 0
    For i = 1 To degree + 1
        metr = metr + 1
        parameters = parameters + metr
    Next i
    hintLabel.Caption = "Select at least " & parameters & " couples of points."
    hintLabel.Enabled = True
    apriori_s = sAprioriTextBox.Text
End Sub
