Dim EntryCount As Single
Dim returnPnt As Variant
Dim returnPnt2 As Variant

Private Sub Frame1_Click()

End Sub

Private Sub Label7_Click()

End Sub

Private Sub UserForm_Initialize()
    EntryCount = 0
End Sub

Private Sub CommandButton6_Click() 'Pros8hkh Shmeioy
On Error Resume Next
Frame2.Enabled = True
Frame3.Enabled = True
Frame4.Enabled = True
ListBox1.Enabled = True
ListBox2.Enabled = True
UserForm2.hide

Dim returnPnt As Variant     '3anadhlwnontai?
Dim returnPnt2 As Variant

   Dim Msg, Style, Title, Help, Ctxt, Response, MyString
Msg = "Choose couple of points."    ' Define message.
Style = vbYesNo    ' Define buttons.
Title = "MsgBox Demonstration"    ' Define title.
Help = "DEMO.HLP"    ' Define Help file.
Ctxt = 1000    ' Define topic
        ' context.
        ' Display message.
Response = MsgBox(Msg, Style, Title, Help, Ctxt)
Do While Response = vbYes  ' User chose Yes.
    MyString = "Yes"    ' Perform some action.
EntryCount = EntryCount + 1
       
returnPnt = ThisDrawing.Utility.GetPoint(, "Input point")
    If Err Then
         If StrComp(Err.Description, "User input is a keyword", 1) = 0 Then
         ' One of the keywords was entered
             Dim inputString As String
             Err.Clear
             inputString = ThisDrawing.Utility.GetInput
             MsgBox "You entered the keyword: " & inputString
         Else
             MsgBox "Error selecting the point: " & Err.Description
             Err.Clear
        End If
    
    End If
ThisDrawing.ModelSpace.AddPoint returnPnt
ThisDrawing.ModelSpace.AddText VBA.Str(EntryCount), returnPnt, 1
ListBox1.AddItem (EntryCount & ")" & VBA.Str(returnPnt(0)) & "," & VBA.Str(returnPnt(1)))

returnPnt = ThisDrawing.Utility.GetPoint(, "Input corresponding point")
ThisDrawing.ModelSpace.AddPoint returnPnt
ThisDrawing.ModelSpace.AddText VBA.Str(EntryCount), returnPnt, 1
    If Err Then
         If StrComp(Err.Description, "User input is a keyword", 1) = 0 Then
         ' One of the keywords was entered
             Err.Clear
             inputString = ThisDrawing.Utility.GetInput
             MsgBox "You entered the keyword: " & inputString
         Else
             MsgBox "Error selecting the point: " & Err.Description
             Err.Clear
         End If
    
    End If
ListBox2.AddItem (EntryCount & ")" & VBA.Str(returnPnt(0)) & "," & VBA.Str(returnPnt(1)))
Response = MsgBox(Msg, Style, Title, Help, Ctxt)
If Response = vbNo Then
''''metrpl = ListBox.Count
         ''''If metrpl > parameters Then
 GoTo 10
         ''''Else: MsgBox "vale"
         'GoTo 50
         ''''End If
End If
Loop ' User chose No.

10:   UserForm2.Show
End Sub
'Private Sub CommandButton1_Click() 'KOYMPI ADD
    'EntryCount = EntryCount + 1
    'ListBox1.AddItem (EntryCount & ") " & TextBox1.Text & ", " & TextBox6.Text)
    'ListBox2.AddItem (EntryCount & ") " & TextBox2.Text & ", " & TextBox5.Text)
'End Sub
Private Sub CommandButton2_Click() 'KOYMPI AFAIRESH_SHMEIOY
    'Ensure ListBox contains list items
    If ListBox1.ListCount >= 1 Then
        'If no selection, choose last list item.
        If ListBox1.ListIndex = -1 Then
            ListBox1.ListIndex = ListBox1.ListCount - 1
        End If
        ListBox1.RemoveItem (ListBox1.ListIndex)
    End If
    
    'Ensure ListBox contains list items
    If ListBox2.ListCount >= 1 Then
        'If no selection, choose last list item.
        If ListBox2.ListIndex = -1 Then
            ListBox2.ListIndex = _
                    ListBox2.ListCount - 1
        End If
        ListBox2.RemoveItem (ListBox2.ListIndex)
    End If
End Sub
Private Sub CommandButton4_Click() 'KOYMPI OK
Dim n1 As Integer
Dim i As Integer
Dim f As Integer
n1 = 0

'ypologismos plh8oys zeygwn shmeiwn
For f = 0 To ListBox1.ListCount - 1 'To 0 Step -1
    n1 = n1 + 1
Next f

sigma_apriori = TextBox4.Text

    'MsgBox parameters
'If parameters = 4 And vathmos = 0 Then
'If index = "Ïìïéüôçôáò" Then
    'Call transformation_SIMILAR(parameters, vathmos, n1, ListBox1, ListBox2)
'Else
Call transformation(parameters, vathmos, n1, ListBox1, ListBox2)
'End If
UserForm4_Report.Show
End Sub
Private Sub CommandButton5_Click() 'KOYMPI AKYRO
'Unload UserForm1
''''ThisDrawing.SelectionSets.Item("SS1").Delete
Unload Me

End Sub
Private Sub CommandButton7_Click() 'koympi EFARMOGH
'For j = 1 To met
'MsgBox "1xekt" & j & xekt(j)
'Next j
Call EFARMOGH(met, kr, lr, xekt)
End Sub
